package GUI;

import Domain.Sistema.SistemaSingleton;
import Utility.Utility;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

public class JFWindow extends javax.swing.JFrame {

    private static JFWindow jFWindow;

    protected static JIFAdministrador jIFAdministrador;
    protected static JIFDigitador jIFDigitador;
    protected static JIFGestor jIFGestor;
    protected static JIFAnalista jIFAnalista;

    protected JMenuBar jF_jMenuBar;
    protected JMenu jF_jMenuFile;
    protected JMenuItem jF_jMenuItemGestionUsuarios;
    protected JMenuItem jF_jMenuItemCrearSolicitud;
    protected JMenuItem jF_jMenuItemGestionAnalisis;
    protected JMenuItem jF_jMenuItemGestionSolicitudes;
    protected JMenuItem jF_jMenuItemLogOut;

    protected JPLogin jF_jPLoginJF;

    private JFWindow() {
        initComponents();
        init();
    }

    public static JFWindow getInstance() {
        if (jFWindow == null) {
            jFWindow = new JFWindow();
        }
        return jFWindow;
    }//getInstance

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemGestionUsuarios = new javax.swing.JMenuItem();
        jMenuItemGestionDigitador = new javax.swing.JMenuItem();
        jMenuItemGestionAnalisis = new javax.swing.JMenuItem();
        jMenuItemGestionSolicitudes = new javax.swing.JMenuItem();
        jMenuItemLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador de Sitios Web Paralelo");
        setResizable(false);

        jMenuFile.setText("File");

        jMenuItemGestionUsuarios.setText("Gestión de Usuarios");
        jMenuItemGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionUsuariosActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemGestionUsuarios);

        jMenuItemGestionDigitador.setText("Gestión Digitador");
        jMenuItemGestionDigitador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionDigitadorActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemGestionDigitador);

        jMenuItemGestionAnalisis.setText("Gestión de Análisis");
        jMenuItemGestionAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionAnalisisActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemGestionAnalisis);

        jMenuItemGestionSolicitudes.setText("Gestión de Solicitudes");
        jMenuItemGestionSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionSolicitudesActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemGestionSolicitudes);

        jMenuItemLogOut.setText("Log out");
        jMenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogOutActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLogOut);

        jMenuBar1.add(jMenuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionUsuariosActionPerformed
        // TODO add your handling code here:
        JFWindow.getInstance().jMenuItemGestionUsuarios.setEnabled(false);
        JFWindow.jIFAdministrador = new JIFAdministrador();
        this.add(jIFAdministrador);
    }//GEN-LAST:event_jMenuItemGestionUsuariosActionPerformed

    private void jMenuItemGestionDigitadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionDigitadorActionPerformed
        // TODO add your handling code here:
        jMenuItemGestionDigitador.setEnabled(false);
        JFWindow.jIFDigitador = new JIFDigitador();
        this.add(jIFDigitador);
    }//GEN-LAST:event_jMenuItemGestionDigitadorActionPerformed

    private void jMenuItemGestionAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionAnalisisActionPerformed
        // TODO add your handling code here:
        JFWindow.getInstance().jMenuItemGestionAnalisis.setEnabled(false);
        JFWindow.jIFAnalista = new JIFAnalista();
        this.add(jIFAnalista);
    }//GEN-LAST:event_jMenuItemGestionAnalisisActionPerformed

    private void jMenuItemGestionSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionSolicitudesActionPerformed
        // TODO add your handling code here:
        JFWindow.getInstance().jMenuItemGestionSolicitudes.setEnabled(false);
        JFWindow.jIFGestor = new JIFGestor();
        this.add(jIFGestor);
    }//GEN-LAST:event_jMenuItemGestionSolicitudesActionPerformed

    private void jMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogOutActionPerformed
        // TODO add your handling code here:
        SistemaSingleton.getInstance().logOut();

        this.jMenuFile.removeAll();
        this.jMenuBar1.setVisible(false);
        this.jF_jPLoginJF = new JPLogin();
        this.add(this.jF_jPLoginJF);

        if (JFWindow.jIFAdministrador != null) {
            this.remove(JFWindow.jIFAdministrador);
            this.jF_jMenuItemGestionUsuarios.setEnabled(true);
            JFWindow.jIFAdministrador.killThreads();
        }
        if (JFWindow.jIFDigitador != null) {
            this.remove(JFWindow.jIFDigitador);
            this.jF_jMenuItemCrearSolicitud.setEnabled(true);
            JFWindow.jIFDigitador.killThreads();
        }
        if (JFWindow.jIFGestor != null) {
            this.remove(JFWindow.jIFGestor);
            this.jF_jMenuItemGestionSolicitudes.setEnabled(true);
            JFWindow.jIFGestor.killThreads();
        }
        if (JFWindow.jIFAnalista != null) {
            this.remove(JFWindow.jIFAnalista);
            this.jF_jMenuItemGestionAnalisis.setEnabled(true);
            JFWindow.jIFAnalista.killThreads();
        }

        JFWindow.getInstance().setTitle("Analizador de Sitios Web Paralelo");
        this.repaint();
    }//GEN-LAST:event_jMenuItemLogOutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemGestionAnalisis;
    private javax.swing.JMenuItem jMenuItemGestionDigitador;
    private javax.swing.JMenuItem jMenuItemGestionSolicitudes;
    private javax.swing.JMenuItem jMenuItemGestionUsuarios;
    private javax.swing.JMenuItem jMenuItemLogOut;
    // End of variables declaration//GEN-END:variables

    private void init() {//done
        this.jF_jMenuBar = this.jMenuBar1;
        this.jF_jMenuFile = this.jMenuFile;
        this.jF_jMenuItemGestionUsuarios = this.jMenuItemGestionUsuarios;
        this.jF_jMenuItemCrearSolicitud = this.jMenuItemGestionDigitador;
        this.jF_jMenuItemGestionAnalisis = this.jMenuItemGestionAnalisis;
        this.jF_jMenuItemGestionSolicitudes = this.jMenuItemGestionSolicitudes;
        this.jF_jMenuItemLogOut = this.jMenuItemLogOut;

        this.jF_jMenuBar.setVisible(false);
        this.jF_jMenuFile.removeAll();
        this.jF_jPLoginJF = new JPLogin();
        this.add(this.jF_jPLoginJF);
    }//init

    public void activarGUIMenuPrincipal() {
        if (SistemaSingleton.getInstance().getUsuario().tipo().contains(Utility.ADMIN)) {
            this.jF_jMenuFile.add(this.jF_jMenuItemGestionUsuarios);
        } else {
            if (SistemaSingleton.getInstance().getUsuario().tipo().contains(Utility.ROL_DIGITADOR)) {
                this.jF_jMenuFile.add(this.jF_jMenuItemCrearSolicitud);
            }
            if (SistemaSingleton.getInstance().getUsuario().tipo().contains(Utility.ROL_GESTOR)) {
                this.jF_jMenuFile.add(this.jF_jMenuItemGestionSolicitudes);
            }
            if (SistemaSingleton.getInstance().getUsuario().tipo().contains(Utility.ROL_ANALISTA)) {
                this.jF_jMenuFile.add(this.jF_jMenuItemGestionAnalisis);
            }
        }
    }//activarGUIMenuPrincipal

}//class
