package GUI;

import Utility.Utility;

public class JFWindow extends javax.swing.JFrame {

    private static JFWindow jFWindow;

    private JFWindow() {
        initComponents();
        init();
    }

    public static JFWindow getInstance() {
        if (jFWindow == null) {
            jFWindow = new JFWindow();
        }
        return jFWindow;
    }//getInstance

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemGestionUsuarios = new javax.swing.JMenuItem();
        jMenuItemCrearSolicitudAnalisis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador de Sitios Web Paralelo");
        setResizable(false);

        jMenuFile.setText("File");

        jMenuItemGestionUsuarios.setText("Gestión de Usuarios");
        jMenuItemGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionUsuariosActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemGestionUsuarios);

        jMenuItemCrearSolicitudAnalisis.setText("Crear Solicitud de Análisis");
        jMenuFile.add(jMenuItemCrearSolicitudAnalisis);

        jMenuBar1.add(jMenuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionUsuariosActionPerformed
        // TODO add your handling code here:
        this.add(new JIFAdministrador());
    }//GEN-LAST:event_jMenuItemGestionUsuariosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JMenuBar jMenuBar1;
    protected javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemCrearSolicitudAnalisis;
    protected javax.swing.JMenuItem jMenuItemGestionUsuarios;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.jMenuBar1.setVisible(false);
        this.jMenuBar1.getMenu(this.jMenuBar1.getComponentIndex(this.jMenuFile)).removeAll();
        this.add(new JPLogin());
    }//init

    public void administradorGUI() {
        this.jMenuBar1.setVisible(true);
        this.jMenuBar1.getMenu(this.jMenuBar1.getComponentIndex(this.jMenuFile)).add(this.jMenuItemGestionUsuarios);
    }//administradorGUI

    public void examinadorGUI(String rol) {

        switch (rol) {
            case Utility.ROL_DIGITADOR:
                this.jMenuBar1.getMenu(this.jMenuBar1.getComponentIndex(this.jMenuFile)).add(this.jMenuItemCrearSolicitudAnalisis);
                break;
            case Utility.ROL_GESTOR:

                break;
            case Utility.ROL_ANALISTA:

                break;
            default:
                throw new AssertionError();
        }

    }//examinadorGUI

}//class
